#!/usr/bin/env ruby

#
# Terminus-Bot: An IRC bot to solve all of the problems with IRC bots.
# Copyright (C) 2012 Terminus-Bot Development Team
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

unless RUBY_VERSION.start_with? "1.9"
  puts "Ruby version 1.9 is required."
  exit -1
end

require 'thread'
require 'logger'
require 'eventmachine'

Dir.chdir(File.dirname(__FILE__))

VERSION = "Terminus-Bot v0.6"
PID_FILE = "var/terminus-bot.pid"

puts VERSION
puts "<http://terminus-bot.net/>"
puts "Released under AGPL3."

if File.exists? PID_FILE
  begin
    pid = File.read(PID_FILE).to_i

    puts "Found PID file with: #{pid}"

    if Process.kill(0, pid)
      puts "Already running as #{pid}"
      exit
    end
  rescue
    # We're good to go. I think.
  end

  puts "PID file appears to be stale. Deleting."
  File.delete(PID_FILE)
end


puts "Loading core files..."

$log = Logger.new(STDOUT)
$log.level = Logger::FATAL

def load_files(dir)
  begin
     Dir["#{File.dirname(__FILE__)}/#{dir}/**/*.rb"].each { |f| load(f) }
  rescue => e
    $log.fatal('preload') { "Failed loading files in #{dir}: #{e}" }
    exit -1
  end
end

# Load all the includes.
load_files "includes"

# TODO: Verify configuration and check for database corruption.

# Launch!
pid = fork do
  EM.run do
    Bot.new
  end
end

puts "Terminus-Bot started as #{pid}"

File.open(PID_FILE, "w") {|f| f.puts pid}

puts "PID written to #{PID_FILE}"

Process.detach pid

