#!/usr/bin/env ruby

#
# Terminus-Bot: An IRC bot to solve all of the problems with IRC bots.
# Copyright (C) 2012 Terminus-Bot Development Team
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

unless RUBY_VERSION.start_with? "1.9"
  puts "Ruby version 1.9 is required."
  exit -1
end

require 'thread'
require 'logger'
require 'eventmachine'

$log = Logger.new(STDOUT)
$log.level = Logger::DEBUG

Dir.chdir(File.dirname(__FILE__))

VERSION  = "Terminus-Bot v0.7"
PID_FILE = "var/terminus-bot.pid"
LICENSE  = "APLG3"

$log.info('preload') { VERSION }
$log.info('preload') { "<http://terminus-bot.net/>" }
$log.info('preload') { "Released under #{LICENSE}." }

unless Dir.exists? "var"
  Dir.mkdir "var"
end

if File.exists? PID_FILE
  begin
    pid = File.read(PID_FILE).to_i

    $log.debug('preload') { "Found PID file with: #{pid}" }

    if Process.kill(0, pid)
      $log.fatal('preload') { "Already running as #{pid}" }
      exit
    end
  rescue
    # We're good to go. I think.
  end

  $log.warn('preload') { "PID file appears to be stale. Deleting." }
  File.delete(PID_FILE)
end


$log.info("preload") { "Loading core files." }

def load_includes

  # These have to be first.
  load "includes/flags.rb"
  #load "includes/database.rb"

  load "includes/config.rb"
  load "includes/events.rb"

  load "includes/string.rb"
  load "includes/time.rb"

  load "includes/users.rb"
  load "includes/ircconnection.rb"
  load "includes/message.rb"
  load "includes/channels.rb"
  load "includes/commands.rb"

  # These have to be last (in this order).
  load "includes/modules.rb"
  load "includes/scripts.rb"
  load "includes/core.rb"

end


load_includes

# TODO: Verify configuration and check for database corruption.

# Launch!
pid = fork do
  EM.run do
    Bot.run
  end
end

# Bot.run changes $log to something else, so just puts this.
puts "Terminus-Bot started as #{pid}. Writing to #{PID_FILE}"

File.open(PID_FILE, "w") {|f| f.puts pid}
Process.detach pid

